.build_image:
  image: docker:latest
  services:
      - name: docker:dind
        command: [ "--experimental" ]
  variables:
    DOCKER_BUILDKIT: 1
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - apk add curl bash
    - mkdir -vp ~/.docker/cli-plugins/
    - curl --silent -L "https://gitlab.com/neurobuilds/setup-dind/-/raw/main/setup_dind.sh" > ~/setup_dind.sh
    - bash ~/setup_dind.sh
    - docker context create tls-environment
    - docker buildx create --use tls-environment
    - docker buildx inspect --bootstrap
  script:
    - docker buildx build --build-arg CI_JOB_TOKEN=$CI_JOB_TOKEN --push -t $TAG .

build_tag:
  extends: .build_image
  variables:
    TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  only:
    - tags

build_branch:
  extends: .build_image
  variables:
    TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_BRANCH
  only:
    - main
    - support/*